version: '3.3'
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=weather_database
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - 3307:3306
    expose:
      - 3306
    networks:
      - app

  backend:
    build:
      context: ../weather_server
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - DB_PORT=3306
      - DB_HOST=db
      - DB_DATABASE=weather_database
      - DB_USERNAME=root
      - DB_PASSWORD=123456
      - CLIENT_URL=http://localhost
    ports:
      - 8000:8000
    volumes:
      - ../weather_server:/app/backend
    depends_on:
      - db
    networks:
      - app
    command: bash -c "php artisan migrate && php artisan db:seed && php artisan serve --host=0.0.0.0"

  nginx:
    image: nginx:1.23.3
    ports:
      - 80:80
    volumes:
      - ../weather_frontend/build:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app

networks:
  app:
